<a href="https://colab.research.google.com/github/Bhavika0/Employee-Salaries-Analysis/blob/master/Panda_machine_Learning_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [0]:
orders = pd.read_table('http://bit.ly/chiporders')
orders.head()

order_id  ...  item_price
0         1  ...      $2.39 
1         1  ...      $3.39 
2         1  ...      $3.39 
3         1  ...      $2.39 
4         2  ...     $16.98 

[5 rows x 5 columns]

In [0]:
# get columns
orders.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [0]:
# get unique item_name
orders.item_name.unique()

array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Chicken Bowl',
       'Side of Chips', 'Steak Burrito', 'Steak Soft Tacos',
       'Chips and Guacamole', 'Chicken Crispy Tacos',
       'Chicken Soft Tacos', 'Chicken Burrito', 'Canned Soda',
       'Barbacoa Burrito', 'Carnitas Burrito', 'Carnitas Bowl',
       'Bottled Water', 'Chips and Tomatillo Green Chili Salsa',
       'Barbacoa Bowl', 'Chips', 'Chicken Salad Bowl', 'Steak Bowl',
       'Barbacoa Soft Tacos', 'Veggie Burrito', 'Veggie Bowl',
       'Steak Crispy Tacos', 'Chips and Tomatillo Red Chili Salsa',
       'Barbacoa Crispy Tacos', 'Veggie Salad Bowl',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Carnitas Soft Tacos',
       'Chicken Salad', 'Canned Soft Drink', 'Steak Salad Bowl',
       '6 Pack Soft Drink', 'Chips and Tomatillo-Red Chili Salsa', 'Bowl',
       'Burrito', 'Crispy Tacos', 'Carnitas Crispy Tacos

In [0]:
# how many unique items are there
orders.nunique()

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

In [0]:
# check datatypes
orders.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [0]:
# item price need to be in float
orders['item_price']=orders.item_price.str.replace('$','').astype(float)

In [0]:
#choice description remove []
orders['choice_description']= orders.choice_description.str.replace('[\[\]]',"")

In [0]:
orders.head()

order_id  ...  item_price
0         1  ...        2.39
1         1  ...        3.39
2         1  ...        3.39
3         1  ...        2.39
4         2  ...       16.98

[5 rows x 5 columns]

In [0]:
# check info - how many rows , dtypes and null
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.7+ KB


In [0]:
# check where null values are wiht what the itemnames are
orders.loc[orders.choice_description.isna()]['item_name'].value_counts()


Chips and Guacamole                      479
Chips                                    211
Bottled Water                            162
Chips and Fresh Tomato Salsa             110
Side of Chips                            101
Chips and Tomatillo Red Chili Salsa       48
Chips and Tomatillo Green Chili Salsa     43
Chips and Tomatillo-Green Chili Salsa     31
Chips and Roasted Chili Corn Salsa        22
Chips and Tomatillo-Red Chili Salsa       20
Chips and Roasted Chili-Corn Salsa        18
Chips and Mild Fresh Tomato Salsa          1
Name: item_name, dtype: int64

In [0]:
# fill na with Reg 
orders.fillna('Reg', inplace=True)

In [0]:
# Top 5 popluar item_name
orders.item_name.value_counts().head()

Chicken Bowl           726
Chicken Burrito        553
Chips and Guacamole    479
Steak Burrito          368
Canned Soft Drink      301
Name: item_name, dtype: int64

In [0]:
import numpy as np

In [0]:
arr =np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [0]:
type(arr)

numpy.ndarray

In [0]:
arr

array([1, 2, 3, 4, 5])

In [0]:
arr.shape


(5,)

In [0]:
arr= np.array([list(range(1,16))])

In [0]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [0]:
a=arr.reshape(5,3)

In [0]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [0]:
a[1:3,1:,]

array([[5, 6],
       [8, 9]])

In [0]:
# arange - start stop and step
a = np.arange(0,14, 2)


In [0]:
a

array([ 0,  2,  4,  6,  8, 10, 12])

In [0]:
np.linspace(1,10,50)# start, stop , aqually space 50 numbers

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [0]:

arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [0]:
# copy function and broadcasting
arr[3:]= 100


In [0]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [0]:
arr1 = arr

In [0]:
a= np.array([list(range(10))])

In [0]:
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [0]:
a[5:]= 100

In [0]:
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])